/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.transur.system;

import controllers.TruckController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class TruckForm extends javax.swing.JPanel {

    /**
     * Creates new form TruckFrom
     */
    public TruckForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        internalField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        patentField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jTextField1.setText("jTextField1");

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Creación de camiones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 70));

        jLabel2.setFont(new java.awt.Font("Roboto ExtraBold", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese el número de interno:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        internalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internalFieldActionPerformed(evt);
            }
        });
        internalField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                internalFieldKeyPressed(evt);
            }
        });
        add(internalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 240, 30));

        jLabel3.setFont(new java.awt.Font("Roboto ExtraBold", 0, 18)); // NOI18N
        jLabel3.setText("Ingrese la patente del camión:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        patentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patentFieldActionPerformed(evt);
            }
        });
        add(patentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 240, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear camión");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 240, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 300, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void internalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internalFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_internalFieldActionPerformed

    private void patentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patentFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addTruck();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void internalFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_internalFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            addTruck();
        }
    }//GEN-LAST:event_internalFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField internalField;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField patentField;
    // End of variables declaration//GEN-END:variables


    private void addTruck() {
        
        if(patentField.getText().isEmpty() || internalField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hay datos faltantes en el formulario, por favor, vuelva a ingresarlos","Error",JOptionPane.INFORMATION_MESSAGE );
        } else {
        
        String patent = patentField.getText();
        int internal = 0;
        try {
            
        internal = Integer.parseInt(internalField.getText());
        TruckController.addTruck(patent, internal);
        patentField.setText("");
        internalField.setText("");
        JOptionPane.showMessageDialog(null, "El camión fue creado correctamente.", "", JOptionPane.INFORMATION_MESSAGE);
        
            } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El campo 'interno' debe ser un número.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}
